name = "qtep"
uuid = "26d1b8cb-0540-4d96-8acd-b575b5bb91e8"
authors = ["Hugo Pag√®s <hugopages@laposte.net>"]
version = "0.1.0"

[deps]
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
LsqFit = "0.15.1"
Plots = "1.40.20"


