name = "qtep"
uuid = "26d1b8cb-0540-4d96-8acd-b575b5bb91e8"
authors = ["Hugo Pag√®s <hugopages@laposte.net>"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ITensors = "0.9.15"
KrylovKit = "0.10.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.1"
Plots = "1.40.20"
Random = "1.11.0"
SparseArrays = "1.11.0"
